// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go-chi-gorilla-wire-workshop/app/domain"
	"go-chi-gorilla-wire-workshop/app/infrastructure"
)

// Injectors from wire.go:

func InitializeApp() *domain.CustomerService {
	customerRepository := infrastructure.NewCustomerInMemoryRepository()
	idRepository := infrastructure.NewIdUuidRepository()
	idService := domain.NewIdService(idRepository)
	customerService := domain.NewCustomerService(customerRepository, idService)
	return customerService
}
