// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

// Injectors from wire.go:

// InitializeApp initializes the application with the necessary dependencies.
func InitializeApp() *CustomerService {
	repository := NewRepository()
	customerService := NewCustomerService(repository)
	return customerService
}

// wire.go:

// NewRepository creates a new Repository instance.
func NewRepository() *Repository {
	return &Repository{}
}
